AWSTemplateFormatVersion: '2010-09-09'
Description: Compute layer - EC2 Instance

Parameters:
  EnvironmentName:
    Type: String

  InstanceType:
    Type: String
    Default: t2.micro

  SubnetId:
    Type: String

  SecurityGroupId:
    Type: String

  InstanceProfileArn:
    Type: String

Mappings:
  RegionAMI:
    us-east-1:
      AMI: ami-0c02fb55956c7d316
    us-west-2:
      AMI: ami-0e34e7b9ca0ace12d

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:        !Ref InstanceType
      ImageId:             !FindInMap [RegionAMI, !Ref AWS::Region, AMI]
      SubnetId:            !Ref SubnetId
      IamInstanceProfile:  !Ref InstanceProfileArn
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-Server"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>${EnvironmentName} Server</h1>
          <p>Built My first nested CloudFormation stack.</p> <hr>
          <p>Munir Miasi is the server administrator.</p>" \
          > /var/www/html/index.html

Outputs:
  InstanceId:
    Value: !Ref EC2Instance

  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp

  WebURL:
    Value: !Sub "http://${EC2Instance.PublicIp}"