AWSTemplateFormatVersion: '2010-09-09'
Description: Compute Layer - EC2 Instance

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  InstanceType:
    Type: String
    Default: t2.micro
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String
  InstanceProfileName:
    Type: String

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      IamInstanceProfile: !Ref InstanceProfileName

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from ${EnvironmentName} - Private Subnet</h1>" > /var/www/html/index.html
          echo "<h2>My Third nested stack - With Private Subnet" >> /var/www/html/index.html

      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-web-server"

Outputs:
  InstanceId:
    Value: !Ref WebServer

  # Removed PublicIP output because instance is in private subnet
  WebURL:
    Value: "Not directly accessible (Private Subnet)"