Resources:
  CoolJananUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "cool-janan"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      Policies:
        - PolicyName: JananCoolPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: IamListAccess
                Effect: Allow
                Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                Resource: '*'

  

  MyInlinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyInlinePolicy
      Users:
        - !Ref CoolJananUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: FullEc2Access
            Effect: Allow
            Action:
              - 'ec2:*'
            Resource: '*'
